/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForecastsRouteImport } from './routes/forecasts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaterialsDailyNeedRouteImport } from './routes/materials.daily-need'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastsRoute = ForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsDailyNeedRoute = MaterialsDailyNeedRouteImport.update({
  id: '/materials/daily-need',
  path: '/materials/daily-need',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forecasts': typeof ForecastsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/materials/daily-need': typeof MaterialsDailyNeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forecasts': typeof ForecastsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/materials/daily-need': typeof MaterialsDailyNeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forecasts': typeof ForecastsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/materials/daily-need': typeof MaterialsDailyNeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/forecasts'
    | '/login'
    | '/settings'
    | '/materials/daily-need'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/forecasts'
    | '/login'
    | '/settings'
    | '/materials/daily-need'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/forecasts'
    | '/login'
    | '/settings'
    | '/materials/daily-need'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ForecastsRoute: typeof ForecastsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  MaterialsDailyNeedRoute: typeof MaterialsDailyNeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasts': {
      id: '/forecasts'
      path: '/forecasts'
      fullPath: '/forecasts'
      preLoaderRoute: typeof ForecastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials/daily-need': {
      id: '/materials/daily-need'
      path: '/materials/daily-need'
      fullPath: '/materials/daily-need'
      preLoaderRoute: typeof MaterialsDailyNeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ForecastsRoute: ForecastsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  MaterialsDailyNeedRoute: MaterialsDailyNeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
